#!/usr/bin/env python3

import sys

def factorize(num):
	for i in range(2, int(num**0.5) + 1):
		if num % i == 0:
			return i, num // i
	return None

def main():
	if len(sys.argv) != 2:
		print("Usage: {} <file>".format(sys.argv[0]))
		sys.exit(1)

	input_file = sys.argv[1]

	with open(input_file, 'r') as file:
		for line in file:
			num = int(line.strip())
			factors = factorize(num)
			if factors:
				print("{}={}*{}".format(num, factors[0], factors[1]))

if __name__ == "__main__":
	main()
